import { ArrowLeft, Check, ChevronRight, Dumbbell, Minus, Pause, Play, Plus, Settings, TimerReset } from 'lucide-react'
import { Heading } from './ui.jsx'
import { clock } from './model.js'

export function WorkoutPage({exercises,workoutMeta,onStart,onOpenPlans,onEdit,onPomodoro}){
  const total=exercises.reduce(function(sum,item){return sum+item.sets.length},0)
  return <>{exercises.length?<><section className="card workout-hero"><div><p className="eyebrow">已载入训练</p><h2>{workoutMeta.title}</h2><p>{workoutMeta.target} · 按动作提示完成训练</p><div className="tags"><span>{exercises.length} 个动作</span><span>{total} 组</span><span>自动组间计时</span></div></div><button className="primary large" onClick={onStart}><Play size={20} fill="currentColor"/>开始训练</button></section>
    <section className="section"><Heading eyebrow="训练内容" title="今日动作"><button className="text-button" onClick={onEdit}><Settings size={16}/>编辑训练</button></Heading><div className="exercise-list">{exercises.map(function(item,index){return <article className="card exercise exercise-with-gif" key={item.id}>{item.gifUrl?<img src={item.gifUrl} alt={item.name+'动作演示'} loading="lazy"/>:<span>{String(index+1).padStart(2,'0')}</span>}<div><h3>{item.name}</h3><p>{item.scheme||item.target+' · '+item.sets.length+' 组 · 休息 '+item.rest+' 秒'}</p>{item.rpe&&<small>{item.rpe} · 休息 {item.rest} 秒</small>}</div><b>{item.sets[0].weight}kg × {item.sets[0].reps}</b><ChevronRight size={18}/></article>})}</div></section></>:<section className="card workout-empty"><Dumbbell size={42}/><p className="eyebrow">尚未载入训练</p><h2>从周计划选择一套动作</h2><p>新账号不会自动生成假的今日训练。前往训练计划，选择周一练胸、周三练背或周五练臀腿后开始。</p><button className="primary" onClick={onOpenPlans}>打开训练计划</button></section>}
    <button className="card focus focus-button" onClick={onPomodoro}><span><TimerReset size={27}/></span><div><p className="eyebrow">自由训练</p><h2>番茄训练计时</h2><p>自定义训练、休息和循环次数。</p></div><strong>开始设置</strong></button></>
}

export function WorkoutSession({exercises,workoutMeta,exerciseIndex,setIndex,doneSets,seconds,rest,restPaused,paused,finished,onBack,onComplete,onPauseRest,onPauseSession,onAddRest,onSkip,onSave,onAdjust,onSkipExercise}){
  const exercise=exercises[exerciseIndex],activeSet=exercise.sets[setIndex],total=exercises.reduce(function(sum,item){return sum+item.sets.length},0)
  return <div className="session"><header><button className="icon" onClick={onBack}><ArrowLeft size={21}/></button><div><strong>{workoutMeta.title}</strong><span>{clock(seconds)} · {doneSets.length}/{total} 组 {paused?'· 已暂停':''}</span></div><button className={paused?'resume-link':''} onClick={onPauseSession}>{paused?'继续':'暂停'}</button></header><div className="session-progress"><span style={{width:(doneSets.length/total*100)+'%'}}/></div>
    {finished?<div className="finish"><span><Check size={42}/></span><p className="eyebrow">训练完成</p><h1>今天很强。</h1><p>完成 {doneSets.length} 组，用时 {Math.max(1,Math.round(seconds/60))} 分钟。</p><div className="finish-stats"><div><b>{doneSets.length}</b><small>完成组数</small></div><div><b>{Math.max(180,Math.round(seconds/60*7.2))}</b><small>估算 kcal</small></div><div><b>{Math.max(1,Math.round(seconds/60))}</b><small>训练分钟</small></div></div><button className="primary large" onClick={onSave}>保存训练记录</button></div>:
    <div className="session-body"><div className="session-title-row"><div className="session-exercise-copy">{exercise.gifUrl&&<div className="session-gif"><img src={exercise.gifUrl} alt={exercise.name+'动作演示'}/>{exercise.attribution&&<small>{exercise.attribution}</small>}</div>}<div><div className="tags"><span>动作 {exerciseIndex+1}/{exercises.length}</span><span>{exercise.target}</span>{exercise.rpe&&<span>{exercise.rpe}</span>}</div><h1>{exercise.name}</h1><p>{exercise.note||exercise.instruction||'保持动作稳定，在可控范围内完成每次重复。'}</p>{exercise.scheme&&<strong className="session-scheme">{exercise.scheme}</strong>}</div></div><button className="secondary compact" onClick={onSkipExercise}>跳过动作</button></div><div className="set-table"><div className="set-row head"><span>组</span><span>重量</span><span>次数</span><span>状态</span></div>{exercise.sets.map(function(set,index){const done=doneSets.includes(exercise.id+'-'+index),active=index===setIndex;return <div className={'set-row '+(active?'active':'')} key={index}><span>{set.label||index+1}</span><b>{set.weight} <small>kg</small></b><b>{set.reps}</b><span className={done?'done':''}>{done?<Check size={16}/>:active?'当前':'待完成'}</span></div>})}</div><div className="active-set"><p className="eyebrow">第 {setIndex+1} 组 · 数据可调整</p><div className="set-controls"><div><button onClick={function(){onAdjust('weight',-2.5)}}><Minus/></button><b>{activeSet.weight}<small>kg</small></b><button onClick={function(){onAdjust('weight',2.5)}}><Plus/></button></div><span>×</span><div><button onClick={function(){onAdjust('reps',-1)}}><Minus/></button><b>{activeSet.reps}<small>次</small></b><button onClick={function(){onAdjust('reps',1)}}><Plus/></button></div></div><button className="primary complete" disabled={paused} onClick={onComplete}><Check size={20}/>{paused?'训练已暂停':'完成本组'}</button></div></div>}
    {rest>0&&<div className="rest-overlay"><div className="rest-sheet"><i/><p className="eyebrow">组间休息</p><strong>{clock(rest)}</strong><p>下一组：{exercises[exerciseIndex].name}</p><div><button onClick={onPauseRest}>{restPaused?<Play/>:<Pause/>}<span>{restPaused?'继续':'暂停'}</span></button><button onClick={onAddRest}><Plus/><span>30 秒</span></button><button onClick={onSkip}><ChevronRight/><span>跳过</span></button></div></div></div>}
  </div>
}
